#pragma once
#include "../../../../../src/erbsland/conf/vr/builder/TypeTraits.hpp"
// !!! WARNING - THIS IS A GENERATED FILE - DO NOT EDIT MANUALLY !!!
// This file was generated by the `generate_header_files.py` script.

